version: "3"

services:
  db:
    image: "mariadb:10.5"
    command: [ "mysqld","--innodb-buffer-pool-size=2G" ]
    volumes:
      - "db_data:/var/lib/mysql"
      - "./.docker/db/initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "${HOST_INTERFACE:-127.0.0.1}:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: on-failure

  wordpress:
    depends_on:
      - db
    image: "wordpress:${WORDPRESS_VERSION}"
    volumes:
      - "./.docker/wordpress/php.ini:/usr/local/etc/php/php.ini:ro"
      - "./wp:/var/www/html"
      - "./.docker/wordpress/.htaccess:/var/www/html/.htaccess"
    ports:
      - "${HOST_INTERFACE}:80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_PREFIX: ${WORDPRESS_DB_PREFIX}
      WP_DEBUG: ${WP_DEBUG}

volumes:
  db_data:
