<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
                                  'key'                   => 'group_60afb437a175a',
                                  'title'                 => 'Unsere-Makler Einstellungen',
                                  'fields'                => array(
                                      array(
                                          'key'               => 'field_60ad99182e07a',
                                          'label'             => 'Die Firma in Zahlen',
                                          'name'              => 'overview_facts',
                                          'type'              => 'repeater',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'collapsed'         => '',
                                          'min'               => 0,
                                          'max'               => 5,
                                          'layout'            => 'table',
                                          'button_label'      => '',
                                          'sub_fields'        => array(
                                              array(
                                                  'key'               => 'field_6111121e2f57e',
                                                  'label'             => 'Icon',
                                                  'name'              => 'icon',
                                                  'type'              => 'select',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '15',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'choices'           => array(
                                                      'handshake' => 'Handschlag',
                                                      'house'     => 'Haus',
                                                      'houses'    => 'Häuser',
                                                      'mail'      => 'E-Mail',
                                                      'people'    => 'Personen',
                                                      'phone'     => 'Telefon',
                                                      'time'      => 'Uhr',
                                                      'bill'      => 'Rechnung',
                                                      'area'      => 'Fläche',
                                                  ),
                                                  'default_value'     => false,
                                                  'allow_null'        => 0,
                                                  'multiple'          => 0,
                                                  'ui'                => 0,
                                                  'return_format'     => 'value',
                                                  'ajax'              => 0,
                                                  'placeholder'       => '',
                                              ),
                                              array(
                                                  'key'               => 'field_111116dbae07b',
                                                  'label'             => 'Wert',
                                                  'name'              => 'value',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '25',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                              array(
                                                  'key'               => 'field_60a33333ae07c',
                                                  'label'             => 'Beschreibung',
                                                  'name'              => 'description',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '60',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                          ),
                                      ),
                                      array(
                                          'key'               => 'field_60afb44045089',
                                          'label'             => 'Über die Firma',
                                          'name'              => 'company',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => array_merge(
                                              getTitleFields('field_688172c124427', 'field_644feff943427'),
                                              [
                                                  array(
                                                      'key'               => 'field_60afb44b4508a',
                                                      'label'             => 'Stichpunkte',
                                                      'name'              => 'list',
                                                      'type'              => 'repeater',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'collapsed'         => '',
                                                      'min'               => 0,
                                                      'max'               => 0,
                                                      'layout'            => 'table',
                                                      'button_label'      => '',
                                                      'sub_fields'        => array(
                                                          array(
                                                              'key'               => 'field_60afb4574508b',
                                                              'label'             => 'Titel',
                                                              'name'              => 'title',
                                                              'type'              => 'text',
                                                              'instructions'      => '',
                                                              'required'          => 0,
                                                              'conditional_logic' => 0,
                                                              'wrapper'           => array(
                                                                  'width' => '30',
                                                                  'class' => '',
                                                                  'id'    => '',
                                                              ),
                                                              'default_value'     => '',
                                                              'placeholder'       => '',
                                                              'prepend'           => '',
                                                              'append'            => '',
                                                              'maxlength'         => '',
                                                          ),
                                                          array(
                                                              'key'               => 'field_60afb45f4508c',
                                                              'label'             => 'Text',
                                                              'name'              => 'text',
                                                              'type'              => 'textarea',
                                                              'instructions'      => '',
                                                              'required'          => 0,
                                                              'conditional_logic' => 0,
                                                              'wrapper'           => array(
                                                                  'width' => '70',
                                                                  'class' => '',
                                                                  'id'    => '',
                                                              ),
                                                              'default_value'     => '',
                                                              'placeholder'       => '',
                                                              'maxlength'         => '',
                                                              'rows'              => 4,
                                                              'new_lines'         => '',
                                                          ),
                                                      ),
                                                  ),
                                                  array(
                                                      'key'               => 'field_60918223abf28',
                                                      'label'             => 'Bild Desktop',
                                                      'name'              => 'picture_desktop',
                                                      'type'              => 'image',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '50',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'return_format'     => 'array',
                                                      'preview_size'      => 'medium',
                                                      'library'           => 'all',
                                                      'min_width'         => '',
                                                      'min_height'        => '',
                                                      'min_size'          => '',
                                                      'max_width'         => '',
                                                      'max_height'        => '',
                                                      'max_size'          => '',
                                                      'mime_types'        => '',
                                                  ),
                                                  array(
                                                      'key'               => 'field_609fff23abf28',
                                                      'label'             => 'Bild Mobil',
                                                      'name'              => 'picture_mobile',
                                                      'type'              => 'image',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '50',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'return_format'     => 'array',
                                                      'preview_size'      => 'medium',
                                                      'library'           => 'all',
                                                      'min_width'         => '',
                                                      'min_height'        => '',
                                                      'min_size'          => '',
                                                      'max_width'         => '',
                                                      'max_height'        => '',
                                                      'max_size'          => '',
                                                      'mime_types'        => '',
                                                  ),
                                              ]
                                          ),
                                      ),
                                      array(
                                          'key'               => 'field_60afb46d4508d',
                                          'label'             => 'Unsere-Makler Sektion',
                                          'name'              => 'agents',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => getTitleFields('field_633372c943427', 'field_44ffeff943427'),
                                      ),
                                  ),
                                  'location'              => array(
                                      array(
                                          array(
                                              'param'    => 'post_template',
                                              'operator' => '==',
                                              'value'    => 'template-agents.php',
                                          ),
                                      ),
                                  ),
                                  'menu_order'            => 0,
                                  'position'              => 'normal',
                                  'style'                 => 'default',
                                  'label_placement'       => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen'        => '',
                                  'active'                => true,
                                  'description'           => '',
                              ));

endif;