<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
                                  'key'                   => 'group_60fd65e8be853',
                                  'title'                 => 'Seiteneinstellungen',
                                  'fields'                => array(
                                      array(
                                          'key'               => 'field_60fd65eb3f5cd',
                                          'label'             => 'Neubauprojekt hervorstellen',
                                          'name'              => 'promote_newbuild',
                                          'type'              => 'true_false',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '50',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'message'           => '',
                                          'default_value'     => 0,
                                          'ui'                => 1,
                                          'ui_on_text'        => '',
                                          'ui_off_text'       => '',
                                      ),
                                      array(
                                          'key'               => 'field_60fd12331212e',
                                          'label'             => 'Services-Foto',
                                          'name'              => 'services_image',
                                          'type'              => 'image',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '50',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'return_format'     => 'id',
                                          'preview_size'      => 'medium',
                                          'library'           => 'all',
                                          'min_width'         => '',
                                          'min_height'        => '',
                                          'min_size'          => '',
                                          'max_width'         => '',
                                          'max_height'        => '',
                                          'max_size'          => '',
                                          'mime_types'        => '',
                                      ),

                                      array(
                                          'key'               => 'field_60fd6b3bb212a',
                                          'label'             => 'Partner',
                                          'name'              => 'partners',
                                          'type'              => 'repeater',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'collapsed'         => '',
                                          'min'               => 0,
                                          'max'               => 0,
                                          'layout'            => 'table',
                                          'button_label'      => '',
                                          'sub_fields'        => array(
                                              array(
                                                  'key'               => 'field_60fd6b4db212b',
                                                  'label'             => 'Partner',
                                                  'name'              => 'details',
                                                  'type'              => 'group',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'layout'            => 'block',
                                                  'sub_fields'        => array(
                                                      array(
                                                          'key'               => 'field_60fd6b64b212c',
                                                          'label'             => 'Name',
                                                          'name'              => 'name',
                                                          'type'              => 'text',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '33',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'placeholder'       => '',
                                                          'prepend'           => '',
                                                          'append'            => '',
                                                          'maxlength'         => '',
                                                      ),
                                                      array(
                                                          'key'               => 'field_60fd6b69b212d',
                                                          'label'             => 'URL',
                                                          'name'              => 'url',
                                                          'type'              => 'text',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '33',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'placeholder'       => '',
                                                          'prepend'           => '',
                                                          'append'            => '',
                                                          'maxlength'         => '',
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key'               => 'field_60fd6b6eb212e',
                                                  'label'             => 'Logo',
                                                  'name'              => 'logo',
                                                  'type'              => 'image',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '33',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'return_format'     => 'array',
                                                  'preview_size'      => 'medium',
                                                  'library'           => 'all',
                                                  'min_width'         => '',
                                                  'min_height'        => '',
                                                  'min_size'          => '',
                                                  'max_width'         => '',
                                                  'max_height'        => '',
                                                  'max_size'          => '',
                                                  'mime_types'        => '',
                                              ),
                                          ),
                                      ),
                                  ),
                                  'location'              => array(
                                      array(
                                          array(
                                              'param'    => 'page_type',
                                              'operator' => '==',
                                              'value'    => 'front_page',
                                          ),
                                      ),
                                  ),
                                  'menu_order'            => 0,
                                  'position'              => 'normal',
                                  'style'                 => 'default',
                                  'label_placement'       => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen'        => '',
                                  'active'                => true,
                                  'description'           => '',
                              ));

endif;