<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
                                  'key'                   => 'group_60fd65e8be853',
                                  'title'                 => 'Seiteneinstellungen',
                                  'fields'                => array(
                                      array(
                                          'key'               => 'field_60fd65eb3f5cd',
                                          'label'             => 'Neubauprojekt hervorstellen',
                                          'name'              => 'promote_newbuild',
                                          'type'              => 'true_false',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '100',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'message'           => '',
                                          'default_value'     => 0,
                                          'ui'                => 1,
                                          'ui_on_text'        => '',
                                          'ui_off_text'       => '',
                                      ),
                                      array(
                                          'key'               => 'field_69933811111b0',
                                          'label'             => 'Neubauprojekt Titel',
                                          'name'              => 'newbuild_settings',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        =>
                                              getTitleFields('field_6099192991927', 'field_6551444442327'),

                                      ),
                                      array(
                                          'key'               => 'field_69933891823b0',
                                          'label'             => 'Immobilien-Angebot Titel',
                                          'name'              => 'buy_settings',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        =>
                                              getTitleFields('field_6444442991927', 'field_6551412345327'),

                                      ),

                                      array(
                                          'key'               => 'field_69933823321b0',
                                          'label'             => 'Hemmadorf',
                                          'name'              => 'hemmadorf_settings',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => array_merge(
                                              getTitleFields('field_6099192113127', 'field_6551714412327'),
                                              [

                                                  array(
                                                      'key'               => 'field_60fd12331212e',
                                                      'label'             => 'Hemmadorf-Foto',
                                                      'name'              => 'hemmadorf_image',
                                                      'type'              => 'image',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '30',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'return_format'     => 'id',
                                                      'preview_size'      => 'medium',
                                                      'library'           => 'all',
                                                      'min_width'         => '',
                                                      'min_height'        => '',
                                                      'min_size'          => '',
                                                      'max_width'         => '',
                                                      'max_height'        => '',
                                                      'max_size'          => '',
                                                      'mime_types'        => '',
                                                  ),
                                                  array(
                                                      'key'               => 'field_6918237b721eb',
                                                      'label'             => 'Hemmadorf Beschreibung',
                                                      'name'              => 'hemmadorf_text',
                                                      'type'              => 'wysiwyg',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '70',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'default_value'     => '',
                                                      'tabs'              => 'all',
                                                      'toolbar'           => 'full',
                                                      'media_upload'      => 1,
                                                      'delay'             => 0,
                                                  ),
                                              ]
                                          )
                                      ),


                                      array(
                                          'key'               => 'field_6190fbb1d7d88',
                                          'label'             => 'Service-Stichpunkte',
                                          'name'              => 'services',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        =>
                                              array_merge(
                                                  getTitleFields('field_6099192113127', 'field_6551714412327'),
                                                  [
                                                      array(
                                                          'key'               => 'field_6190fbbed7d89',
                                                          'label'             => 'Beschreibung',
                                                          'name'              => 'description',
                                                          'type'              => 'wysiwyg',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'tabs'              => 'all',
                                                          'toolbar'           => 'full',
                                                          'media_upload'      => 1,
                                                          'delay'             => 0,
                                                      ),
                                                      array(
                                                          'key'               => 'field_6190fbcbd7d8a',
                                                          'label'             => 'Stichpunkte',
                                                          'name'              => 'points',
                                                          'type'              => 'repeater',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'collapsed'         => '',
                                                          'min'               => 0,
                                                          'max'               => 0,
                                                          'layout'            => 'table',
                                                          'button_label'      => '',
                                                          'sub_fields'        => array(
                                                              array(
                                                                  'key'               => 'field_6190fbe7d7d8c',
                                                                  'label'             => 'Icon',
                                                                  'name'              => 'icon',
                                                                  'type'              => 'select',
                                                                  'instructions'      => '',
                                                                  'required'          => 0,
                                                                  'conditional_logic' => 0,
                                                                  'wrapper'           => array(
                                                                      'width' => '25',
                                                                      'class' => '',
                                                                      'id'    => '',
                                                                  ),
                                                                  'choices'           => array(
                                                                      'brand-tribenet' => 'Netzwerk',
                                                                      'listening'      => 'Ohr mit Ton',
                                                                      'live-support'   => 'Live support',
                                                                      'data'           => 'Datenblatt',
                                                                      'handshake-deal' => 'Handschlag',
                                                                      'photobucket'    => 'Kamera',
                                                                      'holding-hands'  => 'Haltende Hände',
                                                                      'handshake'      => 'Handschlag',
                                                                      'people'         => 'Leute',
                                                                  ),
                                                                  'default_value'     => false,
                                                                  'allow_null'        => 0,
                                                                  'multiple'          => 0,
                                                                  'ui'                => 0,
                                                                  'return_format'     => 'value',
                                                                  'ajax'              => 0,
                                                                  'placeholder'       => '',
                                                              ),
                                                              array(
                                                                  'key'               => 'field_6190fbdbd7d8b',
                                                                  'label'             => 'Titel',
                                                                  'name'              => 'title',
                                                                  'type'              => 'text',
                                                                  'instructions'      => '',
                                                                  'required'          => 0,
                                                                  'conditional_logic' => 0,
                                                                  'wrapper'           => array(
                                                                      'width' => '75',
                                                                      'class' => '',
                                                                      'id'    => '',
                                                                  ),
                                                                  'default_value'     => '',
                                                                  'placeholder'       => '',
                                                                  'prepend'           => '',
                                                                  'append'            => '',
                                                                  'maxlength'         => '',
                                                              ),
                                                          ),
                                                      ),
                                                  ]
                                              ),
                                      ),


                                      array(
                                          'key'               => 'field_60fd6b3bb212a',
                                          'label'             => 'Partner',
                                          'name'              => 'partners',
                                          'type'              => 'repeater',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'collapsed'         => '',
                                          'min'               => 0,
                                          'max'               => 0,
                                          'layout'            => 'table',
                                          'button_label'      => '',
                                          'sub_fields'        => array(
                                              array(
                                                  'key'               => 'field_60fd6b4db212b',
                                                  'label'             => 'Partner',
                                                  'name'              => 'details',
                                                  'type'              => 'group',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'layout'            => 'block',
                                                  'sub_fields'        => array(
                                                      array(
                                                          'key'               => 'field_60fd6b64b212c',
                                                          'label'             => 'Name',
                                                          'name'              => 'name',
                                                          'type'              => 'text',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '33',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'placeholder'       => '',
                                                          'prepend'           => '',
                                                          'append'            => '',
                                                          'maxlength'         => '',
                                                      ),
                                                      array(
                                                          'key'               => 'field_60fd6b69b212d',
                                                          'label'             => 'URL',
                                                          'name'              => 'url',
                                                          'type'              => 'text',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '33',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'placeholder'       => '',
                                                          'prepend'           => '',
                                                          'append'            => '',
                                                          'maxlength'         => '',
                                                      ),
                                                  ),
                                              ),
                                              array(
                                                  'key'               => 'field_60fd6b6eb212e',
                                                  'label'             => 'Logo',
                                                  'name'              => 'logo',
                                                  'type'              => 'image',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '33',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'return_format'     => 'array',
                                                  'preview_size'      => 'medium',
                                                  'library'           => 'all',
                                                  'min_width'         => '',
                                                  'min_height'        => '',
                                                  'min_size'          => '',
                                                  'max_width'         => '',
                                                  'max_height'        => '',
                                                  'max_size'          => '',
                                                  'mime_types'        => '',
                                              ),
                                          ),
                                      ),
                                  ),
                                  'location'              => array(
                                      array(
                                          array(
                                              'param'    => 'page_type',
                                              'operator' => '==',
                                              'value'    => 'front_page',
                                          ),
                                      ),
                                  ),
                                  'menu_order'            => 0,
                                  'position'              => 'normal',
                                  'style'                 => 'default',
                                  'label_placement'       => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen'        => '',
                                  'active'                => true,
                                  'description'           => '',
                              ));

endif;