<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
                                  'key'                   => 'group_60ad166042954',
                                  'title'                 => 'Projekt-Details',
                                  'fields'                => array(
                                      array(
                                          'key'               => 'field_60ad1666ae07a',
                                          'label'             => 'Übersicht-Fakten',
                                          'name'              => 'overview_facts',
                                          'type'              => 'repeater',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'collapsed'         => '',
                                          'min'               => 0,
                                          'max'               => 4,
                                          'layout'            => 'table',
                                          'button_label'      => '',
                                          'sub_fields'        => array(
                                              array(
                                                  'key'               => 'field_60ad16dbae07b',
                                                  'label'             => 'Wert',
                                                  'name'              => 'value',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '25',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                              array(
                                                  'key'               => 'field_60ad16e3ae07c',
                                                  'label'             => 'Beschreibung',
                                                  'name'              => 'description',
                                                  'type'              => 'text',
                                                  'instructions'      => '',
                                                  'required'          => 0,
                                                  'conditional_logic' => 0,
                                                  'wrapper'           => array(
                                                      'width' => '75',
                                                      'class' => '',
                                                      'id'    => '',
                                                  ),
                                                  'default_value'     => '',
                                                  'placeholder'       => '',
                                                  'prepend'           => '',
                                                  'append'            => '',
                                                  'maxlength'         => '',
                                              ),
                                          ),
                                      ),
                                      array(
                                          'key'               => 'field_60ad16fcae07d',
                                          'label'             => 'Tabs',
                                          'name'              => 'tabs',
                                          'type'              => 'flexible_content',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layouts'           => array(
                                              'layout_60ad170a657f0' => array(
                                                  'key'        => 'layout_60ad170a657f0',
                                                  'name'       => 'free',
                                                  'label'      => 'Freitext',
                                                  'display'    => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key'               => 'field_60ad175bae080',
                                                          'label'             => 'Tab-Name',
                                                          'name'              => 'name',
                                                          'type'              => 'text',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'placeholder'       => '',
                                                          'prepend'           => '',
                                                          'append'            => '',
                                                          'maxlength'         => '',
                                                      ),
                                                      array(
                                                          'key'               => 'field_60ad172bae07e',
                                                          'label'             => 'Text',
                                                          'name'              => 'text',
                                                          'type'              => 'wysiwyg',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'tabs'              => 'all',
                                                          'toolbar'           => 'full',
                                                          'media_upload'      => 1,
                                                          'delay'             => 0,
                                                      ),
                                                  ),
                                                  'min'        => '',
                                                  'max'        => '',
                                              ),
                                              'layout_60ad1744ae07f' => array(
                                                  'key'        => 'layout_60ad1744ae07f',
                                                  'name'       => 'list',
                                                  'label'      => 'Liste',
                                                  'display'    => 'block',
                                                  'sub_fields' => array(
                                                      array(
                                                          'key'               => 'field_60ad176eae081',
                                                          'label'             => 'Tab-Name',
                                                          'name'              => 'name',
                                                          'type'              => 'text',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'default_value'     => '',
                                                          'placeholder'       => '',
                                                          'prepend'           => '',
                                                          'append'            => '',
                                                          'maxlength'         => '',
                                                      ),
                                                      array(
                                                          'key'               => 'field_60ad1776ae082',
                                                          'label'             => 'Listen-Elemente',
                                                          'name'              => 'rows',
                                                          'type'              => 'repeater',
                                                          'instructions'      => '',
                                                          'required'          => 0,
                                                          'conditional_logic' => 0,
                                                          'wrapper'           => array(
                                                              'width' => '',
                                                              'class' => '',
                                                              'id'    => '',
                                                          ),
                                                          'collapsed'         => '',
                                                          'min'               => 0,
                                                          'max'               => 0,
                                                          'layout'            => 'block',
                                                          'button_label'      => '',
                                                          'sub_fields'        => array(
                                                              array(
                                                                  'key'               => 'field_60ad17a4ae085',
                                                                  'label'             => 'Bild',
                                                                  'name'              => 'picture',
                                                                  'type'              => 'image',
                                                                  'instructions'      => 'optional',
                                                                  'required'          => 0,
                                                                  'conditional_logic' => 0,
                                                                  'wrapper'           => array(
                                                                      'width' => '20',
                                                                      'class' => '',
                                                                      'id'    => '',
                                                                  ),
                                                                  'return_format'     => 'array',
                                                                  'preview_size'      => 'medium',
                                                                  'library'           => 'all',
                                                                  'min_width'         => '',
                                                                  'min_height'        => '',
                                                                  'min_size'          => '',
                                                                  'max_width'         => '',
                                                                  'max_height'        => '',
                                                                  'max_size'          => '',
                                                                  'mime_types'        => '',
                                                              ),
                                                              array(
                                                                  'key'               => 'field_60ad177bae083',
                                                                  'label'             => 'Titel',
                                                                  'name'              => 'title',
                                                                  'type'              => 'text',
                                                                  'instructions'      => '',
                                                                  'required'          => 0,
                                                                  'conditional_logic' => 0,
                                                                  'wrapper'           => array(
                                                                      'width' => '20',
                                                                      'class' => '',
                                                                      'id'    => '',
                                                                  ),
                                                                  'default_value'     => '',
                                                                  'placeholder'       => '',
                                                                  'prepend'           => '',
                                                                  'append'            => '',
                                                                  'maxlength'         => '',
                                                              ),
                                                              array(
                                                                  'key'               => 'field_60ad178fae084',
                                                                  'label'             => 'Text',
                                                                  'name'              => 'text',
                                                                  'type'              => 'wysiwyg',
                                                                  'instructions'      => '',
                                                                  'required'          => 0,
                                                                  'conditional_logic' => 0,
                                                                  'wrapper'           => array(
                                                                      'width' => '60',
                                                                      'class' => '',
                                                                      'id'    => '',
                                                                  ),
                                                                  'default_value'     => '',
                                                                  'tabs'              => 'all',
                                                                  'toolbar'           => 'full',
                                                                  'media_upload'      => 1,
                                                                  'delay'             => 0,
                                                              ),
                                                          ),
                                                      ),
                                                  ),
                                                  'min'        => '',
                                                  'max'        => '',
                                              ),
                                          ),
                                          'button_label'      => 'Eintrag hinzufügen',
                                          'min'               => '',
                                          'max'               => '',
                                      ),
                                      array(
                                          'key'               => 'field_60ad2e817194c',
                                          'label'             => 'Galerie',
                                          'name'              => 'gallery',
                                          'type'              => 'gallery',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'return_format'     => 'array',
                                          'preview_size'      => 'medium',
                                          'insert'            => 'append',
                                          'library'           => 'all',
                                          'min'               => '',
                                          'max'               => '',
                                          'min_width'         => '',
                                          'min_height'        => '',
                                          'min_size'          => '',
                                          'max_width'         => '',
                                          'max_height'        => '',
                                          'max_size'          => '',
                                          'mime_types'        => '',
                                      ),
                                      array(
                                          'key'               => 'field_60b0eff8eddff',
                                          'label'             => 'Ansprechpartner',
                                          'name'              => 'ansprechpartner',
                                          'type'              => 'user',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'role'              => '',
                                          'allow_null'        => 0,
                                          'multiple'          => 0,
                                          'return_format'     => 'array',
                                      ),
                                      array(
                                          'key'               => 'field_6ffff75bae080',
                                          'label'             => 'Provision',
                                          'name'              => 'provision',
                                          'type'              => 'text',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'default_value'     => '',
                                          'placeholder'       => '',
                                          'prepend'           => '',
                                          'append'            => '',
                                          'maxlength'         => '',
                                      ),
                                  ),
                                  'location'              => array(
                                      array(
                                          array(
                                              'param'    => 'post_type',
                                              'operator' => '==',
                                              'value'    => 'newbuild',
                                          ),
                                      ),
                                  ),
                                  'menu_order'            => 0,
                                  'position'              => 'normal',
                                  'style'                 => 'default',
                                  'label_placement'       => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen'        => '',
                                  'active'                => true,
                                  'description'           => '',
                              ));

endif;


if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
                                  'key'                   => 'group_60ad185a481bc',
                                  'title'                 => 'Wo wird gebaut?',
                                  'fields'                => array(

                                      array(
                                          'key'               => 'field_60ad189e182c4',
                                          'label'             => 'PLZ',
                                          'name'              => 'post_code',
                                          'type'              => 'text',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '50',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'default_value'     => '',
                                          'placeholder'       => '',
                                          'prepend'           => '',
                                          'append'            => '',
                                          'maxlength'         => '',
                                      ),
                                      array(
                                          'key'               => 'field_60ad18a6182c5',
                                          'label'             => 'Ort / Stadt',
                                          'name'              => 'place',
                                          'type'              => 'text',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '50',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'default_value'     => '',
                                          'placeholder'       => '',
                                          'prepend'           => '',
                                          'append'            => '',
                                          'maxlength'         => '',
                                      ),
                                  ),
                                  'location'              => array(
                                      array(
                                          array(
                                              'param'    => 'post_type',
                                              'operator' => '==',
                                              'value'    => 'newbuild',
                                          ),
                                      ),
                                  ),
                                  'menu_order'            => 0,
                                  'position'              => 'acf_after_title',
                                  'style'                 => 'default',
                                  'label_placement'       => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen'        => '',
                                  'active'                => true,
                                  'description'           => '',
                              ));

endif;