<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
                                  'key'                   => 'group_60a137d1e6cf1',
                                  'title'                 => 'Inhalt',
                                  'fields'                => array(
                                      /**
                                       * array(
                                       * 'key'               => 'field_60a137d7921b0',
                                       * 'label'             => 'Services - Erste Sektion',
                                       * 'name'              => 'services_one',
                                       * 'type'              => 'group',
                                       * 'instructions'      => '',
                                       * 'required'          => 0,
                                       * 'conditional_logic' => 0,
                                       * 'wrapper'           => array(
                                       * 'width' => '',
                                       * 'class' => '',
                                       * 'id'    => '',
                                       * ),
                                       * 'layout'            => 'block',
                                       * 'sub_fields'        => array_merge(
                                       * getTitleFields('field_60a125c943127', 'field_612fafc943427'),
                                       * [
                                       *
                                       * array(
                                       * 'key'               => 'field_60a155b2f1f38',
                                       * 'label'             => 'Service-Punkte',
                                       * 'name'              => 'service_points',
                                       * 'type'              => 'repeater',
                                       * 'instructions'      => '',
                                       * 'required'          => 0,
                                       * 'conditional_logic' => 0,
                                       * 'wrapper'           => array(
                                       * 'width' => '',
                                       * 'class' => '',
                                       * 'id'    => '',
                                       * ),
                                       * 'collapsed'         => '',
                                       * 'min'               => 0,
                                       * 'max'               => 0,
                                       * 'layout'            => 'table',
                                       * 'button_label'      => '',
                                       * 'sub_fields'        => array(
                                       * array(
                                       * 'key'               => 'field_60a155c0f1f39',
                                       * 'label'             => 'Titel',
                                       * 'name'              => 'title',
                                       * 'type'              => 'text',
                                       * 'instructions'      => '',
                                       * 'required'          => 0,
                                       * 'conditional_logic' => 0,
                                       * 'wrapper'           => array(
                                       * 'width' => '30',
                                       * 'class' => '',
                                       * 'id'    => '',
                                       * ),
                                       * 'default_value'     => '',
                                       * 'placeholder'       => '',
                                       * 'prepend'           => '',
                                       * 'append'            => '',
                                       * 'maxlength'         => '',
                                       * ),
                                       * array(
                                       * 'key'               => 'field_60a155c7f1f3a',
                                       * 'label'             => 'Text',
                                       * 'name'              => 'text',
                                       * 'type'              => 'textarea',
                                       * 'instructions'      => '',
                                       * 'required'          => 0,
                                       * 'conditional_logic' => 0,
                                       * 'wrapper'           => array(
                                       * 'width' => '70',
                                       * 'class' => '',
                                       * 'id'    => '',
                                       * ),
                                       * 'default_value'     => '',
                                       * 'placeholder'       => '',
                                       * 'maxlength'         => '',
                                       * 'rows'              => 3,
                                       * 'new_lines'         => '',
                                       * ),
                                       * ),
                                       * ),
                                       * ]
                                       * ),
                                       * ),
                                       */
                                      array(
                                          'key'               => 'field_60a13122321b0',
                                          'label'             => 'Suchanfragen - Sektion',
                                          'name'              => 'inquiries',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => array_merge(
                                              getTitleFields('field_60a1441413127', 'field_612f223233427'),
                                              [
                                                  array(
                                                      'key'               => 'field_881825c0f1f39',
                                                      'label'             => '"Mehr Laden" Button-Text',
                                                      'name'              => 'button_text',
                                                      'type'              => 'text',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '100',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'default_value'     => '',
                                                      'placeholder'       => '',
                                                      'prepend'           => '',
                                                      'append'            => '',
                                                      'maxlength'         => '',
                                                  ),
                                              ]
                                          ),
                                      ),
                                      array(
                                          'key'               => 'field_60afffff921b0',
                                          'label'             => 'Services - Zweite Sektion',
                                          'name'              => 'services_two',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => array_merge(
                                              getTitleFields('field_6ffefec943127', 'field_6aaaaac943427'),
                                              [

                                                  array(
                                                      'key'               => 'field_60a15bbaf2f38',
                                                      'label'             => 'Service-Punkte',
                                                      'name'              => 'service_points',
                                                      'type'              => 'repeater',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'collapsed'         => '',
                                                      'min'               => 0,
                                                      'max'               => 0,
                                                      'layout'            => 'block',
                                                      'button_label'      => '',
                                                      'sub_fields'        => array(
                                                          array(
                                                              'key'               => 'field_123455c0f1f39',
                                                              'label'             => 'Titel',
                                                              'name'              => 'title',
                                                              'type'              => 'text',
                                                              'instructions'      => '',
                                                              'required'          => 0,
                                                              'conditional_logic' => 0,
                                                              'wrapper'           => array(
                                                                  'width' => '100',
                                                                  'class' => '',
                                                                  'id'    => '',
                                                              ),
                                                              'default_value'     => '',
                                                              'placeholder'       => '',
                                                              'prepend'           => '',
                                                              'append'            => '',
                                                              'maxlength'         => '',
                                                          ),
                                                          array(
                                                              'key'               => 'field_60a54432f1f3a',
                                                              'label'             => 'Text',
                                                              'name'              => 'text',
                                                              'type'              => 'wysiwyg',
                                                              'instructions'      => '',
                                                              'required'          => 0,
                                                              'conditional_logic' => 0,
                                                              'wrapper'           => array(
                                                                  'width' => '100',
                                                                  'class' => '',
                                                                  'id'    => '',
                                                              ),
                                                              'default_value'     => '',
                                                              'placeholder'       => '',
                                                              'maxlength'         => '',
                                                              'rows'              => 3,
                                                              'new_lines'         => '',
                                                          ),
                                                      ),
                                                  ),
                                              ]
                                          ),
                                      ),
                                      /*
                                      array(
                                          'key'               => 'field_60a33333321b0',
                                          'label'             => 'Kontaktformular',
                                          'name'              => 'contact',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => getTitleFields('field_60aaaaa413127', 'field_612f231332427')
                                      ),
                                      */
                                      /*
                                      array(
                                          'key'               => 'field_6999ff31231b0',
                                          'label'             => 'Alleinvermittlungsauftrag',
                                          'name'              => 'av_section',
                                          'type'              => 'group',
                                          'instructions'      => '',
                                          'required'          => 0,
                                          'conditional_logic' => 0,
                                          'wrapper'           => array(
                                              'width' => '',
                                              'class' => '',
                                              'id'    => '',
                                          ),
                                          'layout'            => 'block',
                                          'sub_fields'        => array_merge(
                                              getTitleFields('field_6ff1111143127', 'field_6aa4223243427'),
                                              [
                                                  array(
                                                      'key'               => 'field_60a1586b5af69',
                                                      'label'             => 'Foto Desktop',
                                                      'name'              => 'picture_desktop',
                                                      'type'              => 'image',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '50',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'return_format'     => 'array',
                                                      'preview_size'      => 'medium',
                                                      'library'           => 'all',
                                                      'min_width'         => '',
                                                      'min_height'        => '',
                                                      'min_size'          => '',
                                                      'max_width'         => '',
                                                      'max_height'        => '',
                                                      'max_size'          => '',
                                                      'mime_types'        => '',
                                                  ),
                                                  array(
                                                      'key'               => 'field_60a188885af69',
                                                      'label'             => 'Foto Mobil',
                                                      'name'              => 'picture_mobile',
                                                      'type'              => 'image',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '50',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'return_format'     => 'array',
                                                      'preview_size'      => 'medium',
                                                      'library'           => 'all',
                                                      'min_width'         => '',
                                                      'min_height'        => '',
                                                      'min_size'          => '',
                                                      'max_width'         => '',
                                                      'max_height'        => '',
                                                      'max_size'          => '',
                                                      'mime_types'        => '',
                                                  ),
                                                  array(
                                                      'key'               => 'field_88817220f1f39',
                                                      'label'             => '"Kontakt aufnehmen" Button-Text',
                                                      'name'              => 'button_text',
                                                      'type'              => 'text',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '100',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'default_value'     => '',
                                                      'placeholder'       => '',
                                                      'prepend'           => '',
                                                      'append'            => '',
                                                      'maxlength'         => '',
                                                  ),
                                              ],
                                              [

                                                  array(
                                                      'key'               => 'field_60a1533111f38',
                                                      'label'             => 'Stichpunkte',
                                                      'name'              => 'service_points',
                                                      'type'              => 'repeater',
                                                      'instructions'      => '',
                                                      'required'          => 0,
                                                      'conditional_logic' => 0,
                                                      'wrapper'           => array(
                                                          'width' => '',
                                                          'class' => '',
                                                          'id'    => '',
                                                      ),
                                                      'collapsed'         => '',
                                                      'min'               => 0,
                                                      'max'               => 0,
                                                      'layout'            => 'table',
                                                      'button_label'      => '',
                                                      'sub_fields'        => array(
                                                          array(
                                                              'key'               => 'field_eeeee432f1f3a',
                                                              'label'             => 'Text',
                                                              'name'              => 'text',
                                                              'type'              => 'textarea',
                                                              'instructions'      => '',
                                                              'required'          => 0,
                                                              'conditional_logic' => 0,
                                                              'wrapper'           => array(
                                                                  'width' => '100',
                                                                  'class' => '',
                                                                  'id'    => '',
                                                              ),
                                                              'default_value'     => '',
                                                              'placeholder'       => '',
                                                              'maxlength'         => '',
                                                              'rows'              => 2,
                                                              'new_lines'         => '',
                                                          ),
                                                      ),
                                                  ),
                                              ]
                                          ),
                                      ),
                                      */
                                  ),
                                  'location'              => array(
                                      array(
                                          array(
                                              'param'    => 'page_template',
                                              'operator' => '==',
                                              'value'    => 'template-sell.php',
                                          ),
                                      ),
                                  ),
                                  'menu_order'            => 0,
                                  'position'              => 'normal',
                                  'style'                 => 'default',
                                  'label_placement'       => 'top',
                                  'instruction_placement' => 'label',
                                  'hide_on_screen'        => '',
                                  'active'                => true,
                                  'description'           => '',
                              ));

endif;